dependencies:
  '@rush-temp/core': 'file:projects/core.tgz'
  '@rush-temp/logger': 'file:projects/logger.tgz'
  reflect-metadata: 0.1.13
  rimraf: 2.6.3
  typescript: 3.3.3333
packages:
  /balanced-match/1.0.0:
    dev: false
    resolution:
      integrity: sha1-ibTRmasr7kneFk6gK4nORi1xt2c=
  /brace-expansion/1.1.11:
    dependencies:
      balanced-match: 1.0.0
      concat-map: 0.0.1
    dev: false
    resolution:
      integrity: sha512-iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==
  /concat-map/0.0.1:
    dev: false
    resolution:
      integrity: sha1-2Klr13/Wjfd5OnMDajug1UBdR3s=
  /fs.realpath/1.0.0:
    dev: false
    resolution:
      integrity: sha1-FQStJSMVjKpA20onh8sBQRmU6k8=
  /glob/7.1.3:
    dependencies:
      fs.realpath: 1.0.0
      inflight: 1.0.6
      inherits: 2.0.3
      minimatch: 3.0.4
      once: 1.4.0
      path-is-absolute: 1.0.1
    dev: false
    resolution:
      integrity: sha512-vcfuiIxogLV4DlGBHIUOwI0IbrJ8HWPc4MU7HzviGeNho/UJDfi6B5p3sHeWIQ0KGIU0Jpxi5ZHxemQfLkkAwQ==
  /inflight/1.0.6:
    dependencies:
      once: 1.4.0
      wrappy: 1.0.2
    dev: false
    resolution:
      integrity: sha1-Sb1jMdfQLQwJvJEKEHW6gWW1bfk=
  /inherits/2.0.3:
    dev: false
    resolution:
      integrity: sha1-Yzwsg+PaQqUC9SRmAiSA9CCCYd4=
  /minimatch/3.0.4:
    dependencies:
      brace-expansion: 1.1.11
    dev: false
    resolution:
      integrity: sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==
  /once/1.4.0:
    dependencies:
      wrappy: 1.0.2
    dev: false
    resolution:
      integrity: sha1-WDsap3WWHUsROsF9nFC6753Xa9E=
  /path-is-absolute/1.0.1:
    dev: false
    engines:
      node: '>=0.10.0'
    resolution:
      integrity: sha1-F0uSaHNVNP+8es5r9TpanhtcX18=
  /reflect-metadata/0.1.13:
    dev: false
    resolution:
      integrity: sha512-Ts1Y/anZELhSsjMcU605fU9RE4Oi3p5ORujwbIKXfWa+0Zxs510Qrmrce5/Jowq3cHSZSJqBjypxmHarc+vEWg==
  /rimraf/2.6.3:
    dependencies:
      glob: 7.1.3
    dev: false
    hasBin: true
    resolution:
      integrity: sha512-mwqeW5XsA2qAejG46gYdENaxXjx9onRNCfn7L0duuP4hCuTIi/QO7PDK07KJfp1d+izWPrzEJDcSqBa0OZQriA==
  /typescript/3.3.3333:
    dev: false
    engines:
      node: '>=4.2.0'
    hasBin: true
    resolution:
      integrity: sha512-JjSKsAfuHBE/fB2oZ8NxtRTk5iGcg6hkYXMnZ3Wc+b2RSqejEqTaem11mHASMnFilHrax3sLK0GDzcJrekZYLw==
  /wrappy/1.0.2:
    dev: false
    resolution:
      integrity: sha1-tSQ9jz7BqjXxNkYFvA0QNuMKtp8=
  'file:projects/core.tgz':
    dependencies:
      reflect-metadata: 0.1.13
      rimraf: 2.6.3
      typescript: 3.3.3333
    dev: false
    name: '@rush-temp/core'
    resolution:
      integrity: sha512-YjcEVGEdVdnAVtrG2uJKhyHFOzM5UiMORP5pcUQ0jU/YF3sWLbstpVVx5x4H2oJbdJDYo/XbDnkx2Kpa1nimXw==
      tarball: 'file:projects/core.tgz'
    version: 0.0.0
  'file:projects/logger.tgz':
    dependencies:
      reflect-metadata: 0.1.13
      rimraf: 2.6.3
      typescript: 3.3.3333
    dev: false
    name: '@rush-temp/logger'
    resolution:
      integrity: sha512-e/WjwD+V/vgJddMQklvP8neKBMEJjhhGC2TTS/ipPdOV2z6m3mKsItasZSa6cohK8aDjvWvb9Rm88vUKn6oBAg==
      tarball: 'file:projects/logger.tgz'
    version: 0.0.0
registry: 'http://localhost:4873/'
shrinkwrapMinorVersion: 9
shrinkwrapVersion: 3
specifiers:
  '@rush-temp/core': 'file:./projects/core.tgz'
  '@rush-temp/logger': 'file:./projects/logger.tgz'
  reflect-metadata: ^0.1.13
  rimraf: latest
  typescript: 3.3.3333
