export const coreFn = () => {
  console.log('coreFn message');
  console.log('new message');
  console.log('new message1');
  console.log('new message2');
  console.log('new message3');
  console.log('new message4');
  console.log('new message5');
  console.log('new message6');
  console.log('new message7');
  console.log('new message8');
  console.log('new message9');
  console.log('new message10');
  console.log('new message11');
  console.log('new message12');
  console.log('new message13');
  console.log('new message14');
  console.log('new message15');
  console.log('new message16');
  console.log('new message17');
};